# Site settings
title: Felix Wöstmann
description: Felix Wöstmann Visitenkarte
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Felix Wöstmann
user_description:  
user_title: Softwareentwickler und  Amateurfotograf
email: kontakt@felixwoestmann.me
github_username:  felixwoestmann
instagram_username:  woestmann.felix

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
